/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMoveVerifier,
  IMoveVerifierInterface,
} from "../../Battleship.sol/IMoveVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[4]",
        name: "_input",
        type: "uint256[4]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMoveVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IMoveVerifierInterface {
    return new Interface(_abi) as IMoveVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMoveVerifier {
    return new Contract(address, _abi, runner) as unknown as IMoveVerifier;
  }
}
