/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Battleship {
  export type MoveStruct = { x: BigNumberish; y: BigNumberish; isHit: boolean };

  export type MoveStructOutput = [x: bigint, y: bigint, isHit: boolean] & {
    x: bigint;
    y: bigint;
    isHit: boolean;
  };

  export type GamePublicMetadataStruct = {
    player1: AddressLike;
    player2: AddressLike;
    player1Hash: BigNumberish;
    player2Hash: BigNumberish;
    moves: Battleship.MoveStruct[];
  };

  export type GamePublicMetadataStructOutput = [
    player1: string,
    player2: string,
    player1Hash: bigint,
    player2Hash: bigint,
    moves: Battleship.MoveStructOutput[]
  ] & {
    player1: string;
    player2: string;
    player1Hash: bigint;
    player2Hash: bigint;
    moves: Battleship.MoveStructOutput[];
  };
}

export interface BattleshipInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createGame"
      | "createVerifier"
      | "game"
      | "joinGame"
      | "moveVerifier"
      | "submitMove"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createGame",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "game", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "joinGame",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "moveVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitMove",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "game", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "moveVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitMove", data: BytesLike): Result;
}

export interface Battleship extends BaseContract {
  connect(runner?: ContractRunner | null): Battleship;
  waitForDeployment(): Promise<this>;

  interface: BattleshipInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createGame: TypedContractMethod<
    [_proof: BytesLike, _boardHash: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  createVerifier: TypedContractMethod<[], [string], "view">;

  game: TypedContractMethod<
    [_gameID: BigNumberish],
    [Battleship.GamePublicMetadataStructOutput],
    "view"
  >;

  joinGame: TypedContractMethod<
    [_gameID: BigNumberish, _proof: BytesLike, _boardHash: BigNumberish],
    [void],
    "nonpayable"
  >;

  moveVerifier: TypedContractMethod<[], [string], "view">;

  submitMove: TypedContractMethod<
    [
      _gameID: BigNumberish,
      _moveX: BigNumberish,
      _moveY: BigNumberish,
      _proof: BytesLike,
      isPreviousMoveAHit: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<
    [_proof: BytesLike, _boardHash: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "game"
  ): TypedContractMethod<
    [_gameID: BigNumberish],
    [Battleship.GamePublicMetadataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<
    [_gameID: BigNumberish, _proof: BytesLike, _boardHash: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "moveVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitMove"
  ): TypedContractMethod<
    [
      _gameID: BigNumberish,
      _moveX: BigNumberish,
      _moveY: BigNumberish,
      _proof: BytesLike,
      isPreviousMoveAHit: boolean
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
